# Generated by Django 5.0.6 on 2024-05-17 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('course', models.CharField(choices=[('CHS', 'Certificate in Health Science'), ('CAT', 'Certificate in Applied Technology'), ('BIT', 'Bachelor of Information Technology'), ('BBT', 'Bachelors in Business Technology'), ('MPH', 'Master of Public Health')], max_length=3)),
                ('entry_scheme', models.CharField(choices=[('AL', 'A-Level certificate'), ('AM', 'Adult/Mature Learning'), ('CE', 'Certificate'), ('DI', 'Diploma'), ('BA', 'Bachelors')], max_length=2)),
                ('intake', models.CharField(choices=[('JAN', 'January Intake'), ('MAY', 'May Intake'), ('AUG', 'August Intake')], max_length=3)),
                ('sponsorship', models.CharField(choices=[('PR', 'Private'), ('GOV', 'Government'), ('BUR', 'Bursary')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('residence', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)])),
            ],
        ),
    ]
